######################
# book (meta) info

title: "Modern Deep Learning Techniques for Natural Language Processing: An Overview"
author: 
  name: Authors

github:
  url: "https://github.com/omarsar/nlp_overview"


########
# more settings

collections:
  chapters:
      output: false

sass:
  sass_dir: css
  style:    expanded

exclude:
- README.md

markdown: kramdown
kramdown:
  math_engine: katex
